---
- name: Web servers playbook
  hosts: webservers
  vars:
    webserver_root: "/var/www/html"
    dbhost: "192.168.33.14"
    dbname: "wordpressdb"
    dbuser: "wpuser"
    dbpasswd: "wpuser"

  roles:
    - apache
    - php
    - wordpress