---
- name: Adding user {{ user }}  
  user:
    name: "{{ user }}"
    shell: /bin/bash
    password: "{{ password | password_hash('sha512') }}"
    append: yes
    groups: sudo
    update_password: always

- name: sudoers
  lineinfile:
    dest: /etc/sudoers
    insertafter: "#includedir /etc/sudoers.d"
    regexp: "{{ user }}?"
    line: "{{ user }}    ALL=(ALL) NOPASSWD:ALL"
    state: present

